CREATE TABLE experience_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experience_id BIGINT NOT NULL REFERENCES experiences(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_experience_images_experience_id ON experience_images(experience_id);